export const postToolDefs = [
  { name: 'create_post', description: 'ツイート/ポストを新規作成する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, text: { type: 'string' }, replyToTweetId: { type: 'string' }, quoteTweetId: { type: 'string' }, mediaIds: { type: 'array', items: { type: 'string' }, description: 'メディアID一覧' }, paidPartnership: { type: 'boolean', description: '有料提携（PR）表示を付ける' } }, required: ['xAccountId', 'text'] } },
  { name: 'create_thread', description: 'スレッド投稿を作成する（複数ツイートを連続投稿）', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, texts: { type: 'array', items: { type: 'string' }, description: 'スレッドの各ツイートテキスト（順番通り）' } }, required: ['xAccountId', 'texts'] } },
  { name: 'delete_post', description: 'Delete a tweet by ID', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, tweetId: { type: 'string' } }, required: ['xAccountId', 'tweetId'] } },
  { name: 'get_post', description: 'Get a tweet with metrics', inputSchema: { type: 'object' as const, properties: { tweetId: { type: 'string' } }, required: ['tweetId'] } },
  { name: 'get_post_history', description: '自アカウントの最近のツイート履歴とメトリクスを取得する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, limit: { type: 'number', description: '取得件数（デフォルト20）' } }, required: ['xAccountId'] } },
  { name: 'get_mentions', description: '自分のツイートへの返信・メンションを取得する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, sinceId: { type: 'string', description: 'このID以降のメンションのみ取得' } }, required: ['xAccountId'] } },
  { name: 'reply_to_post', description: '特定のツイートに返信する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, tweetId: { type: 'string', description: '返信先ツイートID' }, text: { type: 'string' } }, required: ['xAccountId', 'tweetId', 'text'] } },
  { name: 'search_posts', description: 'Search recent tweets', inputSchema: { type: 'object' as const, properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'schedule_post', description: 'ツイートをスケジュール投稿する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, text: { type: 'string' }, scheduledAt: { type: 'string', description: 'ISO 8601形式の投稿日時' } }, required: ['xAccountId', 'text', 'scheduledAt'] } },
];
