export const postToolDefs = [
  { name: 'create_post', description: 'ツイート/ポストを新規作成する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, text: { type: 'string' }, replyToTweetId: { type: 'string' }, quoteTweetId: { type: 'string' }, mediaIds: { type: 'array', items: { type: 'string' }, description: 'メディアID一覧（upload_imageで取得）' }, paidPartnership: { type: 'boolean', description: '有料提携（PR）表示を付ける' } }, required: ['xAccountId', 'text'] } },
  { name: 'upload_image', description: '画像をXメディアとしてアップロードし mediaId を返す。source はローカル画像の絶対パス（png/jpg/webp/gif）または https の画像URL。返った mediaId は create_post / schedule_post の mediaIds、create_article の coverMediaId に渡す。mediaId は24時間で失効するので使う直前にアップロードすること', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, source: { type: 'string', description: 'ローカル画像の絶対パス、または https:// 画像URL' }, mediaCategory: { type: 'string', description: 'tweet_image（デフォルト）/ tweet_gif' } }, required: ['xAccountId', 'source'] } },
  { name: 'create_thread', description: 'スレッド投稿を作成する（複数ツイートを連続投稿）', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, texts: { type: 'array', items: { type: 'string' }, description: 'スレッドの各ツイートテキスト（順番通り）' } }, required: ['xAccountId', 'texts'] } },
  { name: 'delete_post', description: 'Delete a tweet by ID', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, tweetId: { type: 'string' } }, required: ['xAccountId', 'tweetId'] } },
  { name: 'get_post', description: '【X API 課金あり】無料の scrape_post で代替できないか先に検討すること。Get a tweet with metrics', inputSchema: { type: 'object' as const, properties: { tweetId: { type: 'string' } }, required: ['tweetId'] } },
  { name: 'get_post_history', description: '【X API 課金あり】無料の scrape_user_posts で代替できないか先に検討すること。自アカウントの最近のツイート履歴とメトリクスを取得する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, limit: { type: 'number', description: '取得件数（デフォルト20）' } }, required: ['xAccountId'] } },
  { name: 'get_mentions', description: '【X API 課金あり】自分のツイートへの返信・メンションを取得する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, sinceId: { type: 'string', description: 'このID以降のメンションのみ取得' } }, required: ['xAccountId'] } },
  { name: 'reply_to_post', description: '特定のツイートに返信する', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, tweetId: { type: 'string', description: '返信先ツイートID' }, text: { type: 'string' } }, required: ['xAccountId', 'tweetId', 'text'] } },
  { name: 'search_posts', description: '【X API 課金あり】無料の scrape_search で代替できないか先に検討すること。Search recent tweets', inputSchema: { type: 'object' as const, properties: { query: { type: 'string' } }, required: ['query'] } },
  { name: 'schedule_post', description: 'ツイートをスケジュール投稿する(引用RT・メディア対応)', inputSchema: { type: 'object' as const, properties: { xAccountId: { type: 'string' }, text: { type: 'string' }, scheduledAt: { type: 'string', description: 'ISO 8601形式の投稿日時' }, quoteTweetId: { type: 'string', description: '引用するツイートID' }, mediaIds: { type: 'array', items: { type: 'string' } } }, required: ['xAccountId', 'text', 'scheduledAt'] } },
];
